name: just-testing

on:
- push

jobs:
  yoyoyo:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - run: echo "Hello world"
    - name: simple docker action
      uses: ./actions/coverage-matrix/
      with:
        bucket-name: 's3BucketSuperName'
        pat-token: ${{ secrets.PAT_TOKEN }}