name: pwn-request1

on:
  pull_request:
  # pull_request_target

jobs:
  pwn-job-1:
    runs-on: ubuntu-latest
    env:
      SOME_SECRET: ${{ secrets.FUNNY_SECRET }}
    steps:
    - uses: actions/checkout@v2
      # with:
        # ref: ${{ github.event.pull_request.head.sha }}
    - uses: actions/setup-node@v1
    - run: |
        npm install
        npm build
    - run: echo "Hello world"